apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: agro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: sumitapex761/agroserve-backend:latest
        ports:
        - containerPort: 9090
        env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://mysql-service:3306/agrodb
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysql-secret1
                key: root-username
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret1
                key: root-password
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: agro
spec:
  selector:
    app: backend
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
